"""Nombres de país en español e inglés y código ISO alfa-2, para todos los socios.

Radar nombra sus 26 destinos desde ``config``; la ficha de operación muestra
además cualquier socio de Colombia que traiga el Observatorio (unos 190 países
y territorios), así que necesita nombres para todos. Presentación pura: la
tabla va de ISO 3166-1 alfa-3 a (alfa-2, nombre en español, nombre en inglés).
"""

from typing import Final

PAISES: Final[dict[str, tuple[str, str, str]]] = {
    "ABW": ("AW", "Aruba", "Aruba"),
    "AFG": ("AF", "Afganistán", "Afghanistan"),
    "AGO": ("AO", "Angola", "Angola"),
    "AIA": ("AI", "Anguila", "Anguilla"),
    "ALB": ("AL", "Albania", "Albania"),
    "AND": ("AD", "Andorra", "Andorra"),
    "ARE": ("AE", "Emiratos Árabes Unidos", "United Arab Emirates"),
    "ARG": ("AR", "Argentina", "Argentina"),
    "ARM": ("AM", "Armenia", "Armenia"),
    "ASM": ("AS", "Samoa Americana", "American Samoa"),
    "ATG": ("AG", "Antigua y Barbuda", "Antigua and Barbuda"),
    "AUS": ("AU", "Australia", "Australia"),
    "AUT": ("AT", "Austria", "Austria"),
    "AZE": ("AZ", "Azerbaiyán", "Azerbaijan"),
    "BDI": ("BI", "Burundi", "Burundi"),
    "BEL": ("BE", "Bélgica", "Belgium"),
    "BEN": ("BJ", "Benín", "Benin"),
    "BES": ("BQ", "Bonaire, San Eustaquio y Saba", "Bonaire, Sint Eustatius and Saba"),
    "BGD": ("BD", "Bangladés", "Bangladesh"),
    "BGR": ("BG", "Bulgaria", "Bulgaria"),
    "BHR": ("BH", "Baréin", "Bahrain"),
    "BHS": ("BS", "Bahamas", "Bahamas"),
    "BIH": ("BA", "Bosnia y Herzegovina", "Bosnia and Herzegovina"),
    "BLR": ("BY", "Bielorrusia", "Belarus"),
    "BLZ": ("BZ", "Belice", "Belize"),
    "BMU": ("BM", "Bermudas", "Bermuda"),
    "BOL": ("BO", "Bolivia", "Bolivia"),
    "BRA": ("BR", "Brasil", "Brazil"),
    "BRB": ("BB", "Barbados", "Barbados"),
    "BRN": ("BN", "Brunéi", "Brunei"),
    "CAF": ("CF", "República Centroafricana", "Central African Republic"),
    "CAN": ("CA", "Canadá", "Canada"),
    "CHE": ("CH", "Suiza", "Switzerland"),
    "CHL": ("CL", "Chile", "Chile"),
    "CHN": ("CN", "China", "China"),
    "CIV": ("CI", "Costa de Marfil", "Côte d'Ivoire"),
    "CMR": ("CM", "Camerún", "Cameroon"),
    "COD": ("CD", "República Democrática del Congo", "Democratic Republic of the Congo"),
    "COG": ("CG", "Congo", "Congo"),
    "COM": ("KM", "Comoras", "Comoros"),
    "CPV": ("CV", "Cabo Verde", "Cabo Verde"),
    "CRI": ("CR", "Costa Rica", "Costa Rica"),
    "CUB": ("CU", "Cuba", "Cuba"),
    "CUW": ("CW", "Curazao", "Curaçao"),
    "CYM": ("KY", "Islas Caimán", "Cayman Islands"),
    "CYP": ("CY", "Chipre", "Cyprus"),
    "CZE": ("CZ", "Chequia", "Czechia"),
    "DEU": ("DE", "Alemania", "Germany"),
    "DJI": ("DJ", "Yibuti", "Djibouti"),
    "DMA": ("DM", "Dominica", "Dominica"),
    "DNK": ("DK", "Dinamarca", "Denmark"),
    "DOM": ("DO", "República Dominicana", "Dominican Republic"),
    "DZA": ("DZ", "Argelia", "Algeria"),
    "ECU": ("EC", "Ecuador", "Ecuador"),
    "EGY": ("EG", "Egipto", "Egypt"),
    "ESP": ("ES", "España", "Spain"),
    "EST": ("EE", "Estonia", "Estonia"),
    "ETH": ("ET", "Etiopía", "Ethiopia"),
    "FIN": ("FI", "Finlandia", "Finland"),
    "FRA": ("FR", "Francia", "France"),
    "GAB": ("GA", "Gabón", "Gabon"),
    "GBR": ("GB", "Reino Unido", "United Kingdom"),
    "GEO": ("GE", "Georgia", "Georgia"),
    "GHA": ("GH", "Ghana", "Ghana"),
    "GIB": ("GI", "Gibraltar", "Gibraltar"),
    "GIN": ("GN", "Guinea", "Guinea"),
    "GLP": ("GP", "Guadalupe", "Guadeloupe"),
    "GMB": ("GM", "Gambia", "Gambia"),
    "GNQ": ("GQ", "Guinea Ecuatorial", "Equatorial Guinea"),
    "GRC": ("GR", "Grecia", "Greece"),
    "GRD": ("GD", "Granada", "Grenada"),
    "GTM": ("GT", "Guatemala", "Guatemala"),
    "GUF": ("GF", "Guayana Francesa", "French Guiana"),
    "GUM": ("GU", "Guam", "Guam"),
    "GUY": ("GY", "Guyana", "Guyana"),
    "HKG": ("HK", "Hong Kong", "Hong Kong"),
    "HND": ("HN", "Honduras", "Honduras"),
    "HRV": ("HR", "Croacia", "Croatia"),
    "HTI": ("HT", "Haití", "Haiti"),
    "HUN": ("HU", "Hungría", "Hungary"),
    "IDN": ("ID", "Indonesia", "Indonesia"),
    "IND": ("IN", "India", "India"),
    "IRL": ("IE", "Irlanda", "Ireland"),
    "IRN": ("IR", "Irán", "Iran"),
    "IRQ": ("IQ", "Irak", "Iraq"),
    "ISL": ("IS", "Islandia", "Iceland"),
    "ISR": ("IL", "Israel", "Israel"),
    "ITA": ("IT", "Italia", "Italy"),
    "JAM": ("JM", "Jamaica", "Jamaica"),
    "JOR": ("JO", "Jordania", "Jordan"),
    "JPN": ("JP", "Japón", "Japan"),
    "KAZ": ("KZ", "Kazajistán", "Kazakhstan"),
    "KEN": ("KE", "Kenia", "Kenya"),
    "KGZ": ("KG", "Kirguistán", "Kyrgyzstan"),
    "KHM": ("KH", "Camboya", "Cambodia"),
    "KNA": ("KN", "San Cristóbal y Nieves", "Saint Kitts and Nevis"),
    "KOR": ("KR", "Corea del Sur", "South Korea"),
    "KWT": ("KW", "Kuwait", "Kuwait"),
    "LAO": ("LA", "Laos", "Laos"),
    "LBN": ("LB", "Líbano", "Lebanon"),
    "LBR": ("LR", "Liberia", "Liberia"),
    "LBY": ("LY", "Libia", "Libya"),
    "LCA": ("LC", "Santa Lucía", "Saint Lucia"),
    "LIE": ("LI", "Liechtenstein", "Liechtenstein"),
    "LKA": ("LK", "Sri Lanka", "Sri Lanka"),
    "LSO": ("LS", "Lesoto", "Lesotho"),
    "LTU": ("LT", "Lituania", "Lithuania"),
    "LUX": ("LU", "Luxemburgo", "Luxembourg"),
    "LVA": ("LV", "Letonia", "Latvia"),
    "MAC": ("MO", "Macao", "Macao"),
    "MAR": ("MA", "Marruecos", "Morocco"),
    "MCO": ("MC", "Mónaco", "Monaco"),
    "MDA": ("MD", "Moldavia", "Moldova"),
    "MDG": ("MG", "Madagascar", "Madagascar"),
    "MDV": ("MV", "Maldivas", "Maldives"),
    "MEX": ("MX", "México", "Mexico"),
    "MKD": ("MK", "Macedonia del Norte", "North Macedonia"),
    "MLI": ("ML", "Malí", "Mali"),
    "MLT": ("MT", "Malta", "Malta"),
    "MMR": ("MM", "Myanmar", "Myanmar"),
    "MNE": ("ME", "Montenegro", "Montenegro"),
    "MNG": ("MN", "Mongolia", "Mongolia"),
    "MNP": ("MP", "Islas Marianas del Norte", "Northern Mariana Islands"),
    "MOZ": ("MZ", "Mozambique", "Mozambique"),
    "MRT": ("MR", "Mauritania", "Mauritania"),
    "MSR": ("MS", "Montserrat", "Montserrat"),
    "MTQ": ("MQ", "Martinica", "Martinique"),
    "MUS": ("MU", "Mauricio", "Mauritius"),
    "MYS": ("MY", "Malasia", "Malaysia"),
    "NER": ("NE", "Níger", "Niger"),
    "NGA": ("NG", "Nigeria", "Nigeria"),
    "NIC": ("NI", "Nicaragua", "Nicaragua"),
    "NLD": ("NL", "Países Bajos", "Netherlands"),
    "NOR": ("NO", "Noruega", "Norway"),
    "NZL": ("NZ", "Nueva Zelanda", "New Zealand"),
    "OMN": ("OM", "Omán", "Oman"),
    "PAK": ("PK", "Pakistán", "Pakistan"),
    "PAN": ("PA", "Panamá", "Panama"),
    "PER": ("PE", "Perú", "Peru"),
    "PHL": ("PH", "Filipinas", "Philippines"),
    "POL": ("PL", "Polonia", "Poland"),
    "PRI": ("PR", "Puerto Rico", "Puerto Rico"),
    "PRK": ("KP", "Corea del Norte", "North Korea"),
    "PRT": ("PT", "Portugal", "Portugal"),
    "PRY": ("PY", "Paraguay", "Paraguay"),
    "PSE": ("PS", "Palestina", "Palestine"),
    "PYF": ("PF", "Polinesia Francesa", "French Polynesia"),
    "QAT": ("QA", "Catar", "Qatar"),
    "REU": ("RE", "Reunión", "Réunion"),
    "ROU": ("RO", "Rumania", "Romania"),
    "RUS": ("RU", "Rusia", "Russia"),
    "RWA": ("RW", "Ruanda", "Rwanda"),
    "SAU": ("SA", "Arabia Saudita", "Saudi Arabia"),
    "SDN": ("SD", "Sudán", "Sudan"),
    "SEN": ("SN", "Senegal", "Senegal"),
    "SGP": ("SG", "Singapur", "Singapore"),
    "SLE": ("SL", "Sierra Leona", "Sierra Leone"),
    "SLV": ("SV", "El Salvador", "El Salvador"),
    "SMR": ("SM", "San Marino", "San Marino"),
    "SOM": ("SO", "Somalia", "Somalia"),
    "SRB": ("RS", "Serbia", "Serbia"),
    "SUR": ("SR", "Surinam", "Suriname"),
    "SVK": ("SK", "Eslovaquia", "Slovakia"),
    "SVN": ("SI", "Eslovenia", "Slovenia"),
    "SWE": ("SE", "Suecia", "Sweden"),
    "SWZ": ("SZ", "Esuatini", "Eswatini"),
    "SYC": ("SC", "Seychelles", "Seychelles"),
    "SYR": ("SY", "Siria", "Syria"),
    "TCA": ("TC", "Islas Turcas y Caicos", "Turks and Caicos Islands"),
    "TGO": ("TG", "Togo", "Togo"),
    "THA": ("TH", "Tailandia", "Thailand"),
    "TJK": ("TJ", "Tayikistán", "Tajikistan"),
    "TKM": ("TM", "Turkmenistán", "Turkmenistan"),
    "TTO": ("TT", "Trinidad y Tobago", "Trinidad and Tobago"),
    "TUN": ("TN", "Túnez", "Tunisia"),
    "TUR": ("TR", "Turquía", "Türkiye"),
    "TWN": ("TW", "Taiwán", "Taiwan"),
    "TZA": ("TZ", "Tanzania", "Tanzania"),
    "UGA": ("UG", "Uganda", "Uganda"),
    "UKR": ("UA", "Ucrania", "Ukraine"),
    "URY": ("UY", "Uruguay", "Uruguay"),
    "USA": ("US", "Estados Unidos", "United States"),
    "UZB": ("UZ", "Uzbekistán", "Uzbekistan"),
    "VCT": ("VC", "San Vicente y las Granadinas", "Saint Vincent and the Grenadines"),
    "VEN": ("VE", "Venezuela", "Venezuela"),
    "VGB": ("VG", "Islas Vírgenes Británicas", "British Virgin Islands"),
    "VIR": ("VI", "Islas Vírgenes de EE. UU.", "U.S. Virgin Islands"),
    "VNM": ("VN", "Vietnam", "Vietnam"),
    "YEM": ("YE", "Yemen", "Yemen"),
    "ZAF": ("ZA", "Sudáfrica", "South Africa"),
    "ZMB": ("ZM", "Zambia", "Zambia"),
    "ZWE": ("ZW", "Zimbabue", "Zimbabwe"),
}


def nombre(iso3: str, lang: str) -> str | None:
    """Nombre del país en ``lang`` (``"es"`` o ``"en"``), o ``None`` si no está en la tabla."""
    fila = PAISES.get(iso3.upper())
    if fila is None:
        return None
    return fila[2] if lang == "en" else fila[1]


def iso2(iso3: str) -> str | None:
    """Código ISO alfa-2, o ``None`` si no está en la tabla."""
    fila = PAISES.get(iso3.upper())
    return fila[0] if fila else None
